export const apiEndPoints = {
  LOGIN_API: "/onboarding/login",
  ADD_STUDENT: "/student/create",
  EDIT_STUDENT: "/student/edit",
  DELETE_STUDENT: "/student/delete",
  GET_STUDENT_LIST: "/student",
  GET_STUDENT_BY_ID: "/student",
  UPLOAD: "/file/upload",
  GET_COURSE_LIST: "/course",
  GET_COURSE_BY_ID: "/course",
  ADD_COURSE: "/course/create",
  // EDIT_COURSE: "/course/edit",
  DELETE_COURSE: "/course/delete",
  GET_SUBJECT_LIST: "/course/subjects",
  ADD_SUBJECT: "/course/subject/create",
  // EDIT_SUBJECT:"/course/subject/edit",
  DELETE_SUBJECT: "/course/subject/delete",
  ADD_STUDENT_MARKS: "/marks",
  GET_STUDENT_MARKS: "/marks",
  EDIT_STUDENT_MARKS: "/marks",
  DELETE_STUDENT_MARKS: "/marks",
  GET_ALL_STUDENT_MARKS: "/marks/list",
  UPDATE_STUDENT_MARKS: "/marks",
  ADD_EXAM: "/exam",
  GET_EXAMS_LIST: "/exam",
  GET_EXAM_BY_ID: "/exam",
  EDIT_EXAM: "/exam",
  DELETE_EXAM: "/exam",
  GET_NOTICE: '/notice',
  ADD_NOTICE: '/notice',
  DELETE_NOTICE: '/notice',
  GET_INSTITUTE_SETTINGS: '/institute-settings',
  GET_INSTITUTE_SETTINGS_BY_ID: '/institute-settings',
  UPDATE_INSTITUTE_SETTINGS: '/institute-settings',
  DELETE_INSTITUTE_SETTINGS: '/institute-settings',
  ADD_INSTITUTE_SETTINGS: '/institute-settings',
  GET_CERTIFICATE_TEMPLATES: '/certificate/template',
  ADD_CERTIFICATE_TEMPLATE: '/certificate/template',
  UPDATE_CERTIFICATE_TEMPLATE: '/certificate/template',
  DELETE_CERTIFICATE_TEMPLATE: '/certificate/template',
  ISSUE_CERTIFICATE: '/certificate/issue',
  GET_ISSUED_CERTIFICATES: '/certificate/issued',
};

export type APIENDPOINTS_TYPE = keyof typeof apiEndPoints;
